---
- name: Get beaker tasks list
  uri:
    url: https://beaker-project.org/tasks/
    return_content: true
  register: beaker_tasks

- name: Parse rpms list
  set_fact:
    rpms:
      "{{ beaker_tasks.content.split('\n') | select('search', '.rpm') |
      map('regex_replace',
      '<tr><td valign=\"top\">.*<a href=\"(.*.rpm)\">.*</td></tr>',
      '\\1') | list }}"

- name: Fetch Beaker default tasks
  get_url:
    dest: '/tmp/{{ item }}'
    url: 'https://beaker-project.org/tasks/{{ item }}'
  with_items: '{{ rpms }}'

- name: Upload Beaker default tasks
  shell: bkr task-add /tmp/{{ item }}
  args:
    creates: "{{ data_dir }}/beaker/rpms/{{ item }}"
  become: true
  with_items: '{{ rpms }}'
  ignore_errors: true
